spring:
  jackson:
    deserialization:
      fail-on-unknown-properties:
        true

  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springfamework:
              security: DEBUG

my-app:
  admin-password: admin
  admin-username: admin@email.com
  user-username: hkh@email.com
  user-password: 1234
  client-id: my-app
  client-secret: pass
